apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:+9/r1vDFB6RuxIgJ5q+czz2p4I0uF7cisAcJRD0zJsIsmQey,iv:AmC6BvY/ntLJkRf8/yTIJNuu8cMiCLyRqD7J2MZIKiI=,tag:iehes8KpROZIHLDgVgC0Lw==,type:str]
    credentials.json: ENC[AES256_GCM,data:aZ9zIglCCOnVJO1XDBPmkpmK3vowU/TRsRTVTdQHjCZaSD0gRE2gxRoqTLsdJgeADnmC5KSMG497s2yapy7cKBhv68WWvnhP0dePBzzONkmeGnln65U6jJYHh4czxdtXKJ27QSsdTWjZxVn6aXZpO5+4LpRW3xuz4z3oIEULVWd/MmjgsurunZGyM/ie3ITQ+gpabzltTToWKZuduuQdx/PMy/5a4zF5siJXd87HZg==,iv:rHubK89TjgsNf0xWNlvkQL+HBnuYlVj+mZuPz+D7jzM=,tag:frSQgAMRR64ghFEokbfrvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tzmtwftxgy5ayyycw4daz6hareh547pymdlr8acqlk4t7teh5prq4f0c4l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnL1dmclNLWmQzL0Y0TXNP
            aDJVUlJjMWhzSjA2TTNIRG1JaDlrS1U5QUVvCnMxMzJneWE3UW4rK28zZDdrODlk
            RHp5N2tYK0g3L1k1dmZ5K1lZak5PTWMKLS0tIG80Kzg0Q2JwNytCWXRiYkw1UVph
            azVCaTJpOHNrK0kvSlpHYURweG5aWW8K0Lb0jKbGKj+urjkgG95I4mlWOs0hUpZl
            XC4qJtUP5qCrteClMei55dUCyuFyejI1lL85sLlzoAmA3i7CAM09Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-17T09:02:29Z"
    mac: ENC[AES256_GCM,data:xqTIwB5GFG83/9AnhGAEl/GakLjoa0bsJb/ys6NPsBBICrIGsXfYNBOIOvSgLv2B0SWCcd9l+3izdDgLBPxDG2jfxN/6CtD4dqgRG0RYCgwU2IED3al9d+7IDWe3ig27QrLKcoSETHdqe/+LLjvY3eRKWBgQ0jTegBlal8DPux0=,iv:GNuEdakSBa2TjZS3550LZV4qWfqEWBqLuTx+kVQLsNc=,tag:57RMygElvrmtjanAslDAEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
