apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:0/iHy+ditrgGEEbyJHSDfkaCbssnFft4inYKZtWY4a5l7hv5,iv:K2MuPevVVVpSq2gIdGvssu7q3p9lbC5HGTl9bgKVN/Q=,tag:VNvVkvTQfpmSJ+kGATEhdQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:BmsBkaZRBb4kUL04n4mCpkTckEaVd+syJ1J+Hw9Al9F97vk8PSzexMz41KQ08J4kI6HF8LiZ80eyTKsXHxSYVCGG303Ezgj/rjyuHTiTPXVviugrCI2PiqLaqt4aDnjHhw5biDiX6C4lhv7ijDFts1OBRFvV1XJbDdzIZg43y+0VD31T6qRxZzdgyV+lhIwvr7VNv4uFCAqQlmt6wrixxD+Cz10fLlPbeqIvZdlB9w==,iv:+R4U4aeGEi7DMhJ3os/yyb6U1bOhch9X2pLmt/7pjyI=,tag:nSCxAoMCWNMt/IxQ0o8r1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tzmtwftxgy5ayyycw4daz6hareh547pymdlr8acqlk4t7teh5prq4f0c4l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRkxvSi90bzlxS2pEOFVo
            bTlFM0RDa0w4bGoxa05oNVFpYWdJVThZSGhRClVvK3U5MU5IRmhtZGJ3dzlHMVc5
            WEFDL1RhRXZ6QkFFblpVbm1Bb2YyWDgKLS0tIHB1cmdpSmRaVEc2bEhDeTE5eUQx
            NThwL2VuK0VHMzNJenAzT0UvQm4vVDAKy/QlkT+N2K1Gx87dAPBWAQqyobjnbqZr
            fWKXnGmZsccDrhm+ca8PbRn+SOQM4H8D3WBBTazIE9kiWg4Xgp4SeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-06T00:20:54Z"
    mac: ENC[AES256_GCM,data:PoMBGfFNM8Bqr4WSjTqQItAP+ZquU36U1siQWxiO1dacZ6dYh9O8vqALm5qEN0NhMhHfgIbwkX2x/Y+B0w50o9T8VaWn06+2lufjT41mqUs+DfR2VW64cgNTxixV+FDb5rkghe1C2R3kFNQUCYdoWoDbUGlKhT99X5Na1+QGtKM=,iv:kLUS7q4OYDmpWrptEaY3rr3cS8B7lcw+R8WVL83lDFA=,tag:XSOkAcqthKXmBadO30QSqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
