apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:zwLPgZ/DqvzwRoke+u/EKpTSB23KCp922MZZ32bICR7F4xCT,iv:xSfXqVl/IAU5JC+6aDkH6Kgbmtr5FpGVAcYtS8yZd1k=,tag:wSjOsDNDNU7vW7d15B5hcA==,type:str]
    credentials.json: ENC[AES256_GCM,data:4kMZM+9ikrlZQ1rci/pf7tLn21DHwxUPWXz+JfwIk1wE24kmqapKx8KbKPrRvVOo5WiksyntXRTN1DjdRi7Y+TF21kyU2gQmHjG/nOs1IQWa17Ek1VJJpmiSC7USUjRMB4z9sYww8It/MsT9g8sakTVUWYqIv8OlRMuC6Sh1mz65eBakvJtTjyPySVgS0edeZ0hmYPyoKXGxQKv6xXy6DRIUdRF6PSFx8pkXuqkHUw==,iv:f9QxTTNM8ZR3toXrPhkYzFOCKzd387NI+JH1QHJfuBY=,tag:ccJkUByHXrVhBZI8Fyof5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tzmtwftxgy5ayyycw4daz6hareh547pymdlr8acqlk4t7teh5prq4f0c4l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeGJ5ajRpdWNmRU5hNC9O
            cG9tcEpTa1ZDOFk3M0xoNFlUaGo5TGRRTlJRCkNtbUtYY2hQZy9LeCtQSXFnM3pj
            NmJFZm8zT3h5RFdwUjZlcnBRR3ZiVDgKLS0tIERuNTBqRTFFVjRmSkRFTW05c3pi
            ZDlyVFkvbjJZK25pZHhpMHBEM2tJK0UKGU/L3ABgSFITccWXCI++ZaFMVOGSo+pw
            QlZYdZGj7fOe/694y5rM6sl3FqLdkVF8m/ZlhEop3e98rrPxOyNtYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T05:11:17Z"
    mac: ENC[AES256_GCM,data:KtHzc5XUUVpBpYImfeCNwfRcRSxyCR7SD/msOMn92lhbc8TxqNo6QeQ1DHKW6lhH6g66IzQqjAe9XwBWWUnQ5wz1rqXi8GlYokFWRAKIpPsGDMM+0vnmdoQ6QGoWT/qhX8LXb36eabHpoCpuEUSbRHzWjh2mVanugO/PXn/2hdQ=,iv:MDQxkBtXyXsk6w8BQHZz8d/75XRmipo11JwVdJAEskE=,tag:RX/VMCHhwZeE1HRmojh72Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
