---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume2/k3s
    server: 192.168.1.22

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
