apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:lZNHbjF3yiEX9DYEbCzCWYeejnNi0m5bF6PLZO4ALoPXzlYWMA==,iv:cULFPYL8/HSWbx29zo0lCJ9z35Osoz3PFMpjHz15nBw=,tag:P2nxF7v/7cdydVhtFlmcpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tzmtwftxgy5ayyycw4daz6hareh547pymdlr8acqlk4t7teh5prq4f0c4l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObWdudllUQ2l4THpWRmlh
            Q0lPa2ZvVCtxSjNhdWVkQ1dMTWFOWjFoZ1V3CjZSVWpjNElTYkRzOHZweDM0SC9y
            TElqcGtyc3NCVURxWUNZMlRYNzIyejAKLS0tIGMrejNVVkRrQndDTWZOZ0pWV21o
            MHh1MlVxR2tvU3BvcllmRUVwdk5KN0kKs2zfPlTH4oAUUtC+qmnWCMDM44nItDRO
            VIWQeokp886UMTGmpJxjbqUDEpZc5xXrzch3JSL8A443HP/O8/PsgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-06T01:23:47Z"
    mac: ENC[AES256_GCM,data:MGNdabzsO2vyy1zcGXfvz6B7FTcLu+RwugHx/pD7B88TDVuuhlC7dAKP25AfrqbF5NNU85p73DpRiC2nx69ShK1hJkbd3kqR8X1XW8M0wcGqhlc1n6YuCzK9pBMZcUFNtKmou4qg6F/c24fO04BfE8jcIXJOuzbC2S1k4qlCK2g=,iv:tIOq5BKSrydOkBam4Y4h/qO/lYE91OymNWzUEc3tkck=,tag:W2TLQ5x2QUCJyfvEesA3tg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
