apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:kI4BmGi5GwQzIcUfM9X4ECMPn/cebXAvvxO2PZxFyUMUPvl6MJx2mw==,iv:gmMwPZB3hwIMDGdVBKDIVZPghZc8xbsTpOrZglAe0ls=,tag:El9/mUff8prN/XDzB4/fpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tzmtwftxgy5ayyycw4daz6hareh547pymdlr8acqlk4t7teh5prq4f0c4l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnY0tITjlxcUpvTVl2L25M
            ZVdtUmd3d1JFUmtNU01FSEhIM296am5kV0FvCkxEa3ZKVFNpM2RESUk3ZmE3MGs0
            bWRROVkwZ1VXSkJrdklrMTlseEdOME0KLS0tIDM5MHllN1hHcVY4Sjlna0JneTB3
            RVkxZFZkZUV4c2dMRHlVTDdMSElMSkEKyJLJMsfENpSvDfTsoAZGiNx7xYJXHND6
            DjShJEhVuoCcF9QSA3zbBQ9cSLwX9nagvjc3oe/ZJu203zleU0lbBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-08T03:05:23Z"
    mac: ENC[AES256_GCM,data:mys5sriHZtDAki4Uh0yocnFV+Krf9u0rZnHJ4RwA8bSatFpPok05oHyF9wwxTfA8Y3weyOn8wHWdga8kEos4J93yHJueraOuNIuQ+I8VK8uEMUtUUCs0/43d7e2ZuD014e7rRehtXUUAlVgdx88lOZH0JVqCDjAFd70C6RWCjGw=,iv:CKsxPr+SznfiSKiRMDqwR8TiSxLSjW5qOjLq+uFpf5c=,tag:7QwA4rB8B1Pc4JDmA9Nwmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
