---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://zebernst.github.io/synology-csi-talos
      chart: synology-csi
      version: 0.9.7
      sourceRef:
        kind: HelmRepository
        name: synology-csi
        namespace: flux-system
      interval: 30m
  values:
    clientInfoSecret:
      create: false
      name: synology-csi-secret
    storageClasses:
      synology-iscsi-delete:
        parameters:
          dsm: 192.168.1.22
          fstype: ext4
          location: '/volume1'
          protocol: iscsi
      synology-iscsi-retain:
        parameters:
          dsm: 192.168.1.22
          fstype: ext4
          location: '/volume1'
          protocol: iscsi
        isDefault: true
    volumeSnapshotClasses:
      synology-iscsi-delete:
        deletionPolicy: Delete
      synology-iscsi-retain:
        deletionPolicy: Retain
