apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:9FkSzVQEalcACeYHDk3e1cZR+a6fZ1Qkg/V+Z13I0FTvOg5AFVeuJA==,iv:h1bat4YtOthkWvJN6VGf0YFu1OJEmpLtdLKk6/kto1s=,tag:y4+aqJp+8HszLd1gZzL6jg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tzmtwftxgy5ayyycw4daz6hareh547pymdlr8acqlk4t7teh5prq4f0c4l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQjRpT2IrVlg2RWZadnpx
            cE42cXlRaDl4VTh4OHhVQkVIeFhRdk1BempjCmR6RVJnRTd0d0xvMWVDeFBJWlFD
            YkdQeUlqcnZ5N2EzcTl3KzVkTFM2blUKLS0tIDRDc3JJTEMxZFNuNFVHRkV5MmFV
            aXd3bkZHVVdlR2JJeE42K3lHYmF4VXcKMSbz2G5iBhQEUfgwb+I8ZBEYToLIkZRS
            QMCk1riXnYc7yFD3u0tQeLxidQyv7zxXOd/NRkjqJSj8fFHtISkJmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T05:11:17Z"
    mac: ENC[AES256_GCM,data:/U80lEGVOxQLH/TWIJVn5tmKZlGMcFoAXz7DqFZ/bi22m3pdUKIRIWammFoMr8tf9PGN9m3etou+h4WwB7qiv6Jg56i7L0ciRwZgS54s5XVlx7C7jPlwtkte/wtoO1E1FFKLLVS1fqPn41wzSIeFOww8gPa1/d8HKp7cdZ/p8R4=,iv:H/xzIe/lME7/0svMMxaYTOw4WQYTn071s6+yyHFdG4E=,tag:FbC2Gnsaenm1FPF3trV5HQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
